# POSTGRESQL
- name: Install PostgreSQL
  action: apt name={{ postgresql }}

- name: Install postgres dev
  action: apt name=postgresql-server-dev-all

- name: create db user
  sudo: yes
  sudo_user: postgres
  postgresql_user: name=vagrant password=secret role_attr_flags=SUPERUSER

- name: create dbs
  sudo: yes
  sudo_user: postgres
  postgresql_db: name=teste owner=vagrant
                 encoding='UTF-8' lc_collate='en_US.UTF-8' lc_ctype='en_US.UTF-8' template='template0'
                 state=present

#MONGODB
- name: install mongodb
  apt: name=mongodb